package klassdiagram;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Graphics;
import java.util.ArrayList;


/**
 *
 * @author afnka01
 */
public class FormJPanel extends javax.swing.JPanel {

    ArrayList<Form> former = new ArrayList<>();
    FileManager fmgr = new FileManager();
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnClear = new javax.swing.JButton();
        rbtnCirkel = new javax.swing.JRadioButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        btnHamta = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnClear.setText("Rensa");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCirkel);
        rbtnCirkel.setSelected(true);
        rbtnCirkel.setText("Cirkel");

        buttonGroup1.add(rbtnRektangel);
        rbtnRektangel.setText("Rektangel");

        buttonGroup1.add(rbtnTriangel);
        rbtnTriangel.setText("Triangel");

        btnHamta.setText("Hämta");
        btnHamta.setBorderPainted(false);
        btnHamta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamtaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rbtnCirkel)
                .addGap(18, 18, 18)
                .addComponent(rbtnRektangel)
                .addGap(18, 18, 18)
                .addComponent(rbtnTriangel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHamta)
                    .addComponent(btnSpara)
                    .addComponent(btnClear))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnCirkel)
                        .addComponent(rbtnRektangel)
                        .addComponent(rbtnTriangel)))
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addGap(18, 18, 18)
                .addComponent(btnHamta)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        this.former.clear();
        repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    int x = evt.getX();
    int y = evt.getY();
        System.out.println("x:"+x);
    int b = (int) (Math.random()*301)+5;
    int h = (int) (Math.random()*301)+ 5;
    
if(this.rbtnTriangel.isSelected()){
            Form t = new Triangel(x, y, b, h, true);
            former.add(t);
        }
        else if(this.rbtnRektangel.isSelected()){
            Form r = new Rektangel(x, y, b, h, true);
            former.add(r);
        }
        else if(this.rbtnCirkel.isSelected()){
            Form c = new Cirkel(x-(h/2), y-(h/2), h, true);
            former.add(c);
        }
        repaint();
    
    

// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnHamtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamtaActionPerformed
    former = fmgr.readFromFile(); 
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnHamtaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    fmgr.saveToFile(former);  
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaActionPerformed
    // anropa draw metoden
    // Samt supperklassen med en bokstav
    // 

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < former.size(); i++) {
            former.get(i).draw(g);
        }
        
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHamta;
    private javax.swing.JButton btnSpara;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbtnCirkel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    // End of variables declaration//GEN-END:variables
}

