package klassdiagram;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Graphics;
import java.util.ArrayList;


/**
 *
 * @author afnka01
 */
public class FormJPanel extends javax.swing.JPanel {

    ArrayList<Form> former = new ArrayList<>();

    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnCirkel = new javax.swing.JButton();
        btnTria = new javax.swing.JButton();
        btnRekt = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCirkel.setText("cirkel");
        btnCirkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirkelActionPerformed(evt);
            }
        });

        btnTria.setText("Triangel");
        btnTria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriaActionPerformed(evt);
            }
        });

        btnRekt.setText("Rektangel");
        btnRekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRektActionPerformed(evt);
            }
        });

        btnClear.setText("Rensa");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCirkel)
                .addGap(34, 34, 34)
                .addComponent(btnRekt)
                .addGap(31, 31, 31)
                .addComponent(btnTria)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCirkel)
                    .addComponent(btnRekt)
                    .addComponent(btnTria)
                    .addComponent(btnClear))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCirkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirkelActionPerformed
        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int r = (int) (Math.random() * 101);
        Form C = new Cirkel(x, y, r, true);
        former.add(C);
        repaint();

// TODO add your handling code here:
        // skapa en cirkel och lägga den i en lista.
        // anropa repaint se pdf-filen kapitel, blad 7
    }//GEN-LAST:event_btnCirkelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRektActionPerformed
        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int b = (int) (Math.random() * 301);
        int h = (int) (Math.random() * 301);
        Form r = new Rektangel(x, y, b, h, true);
        former.add(r);
        repaint();

    }//GEN-LAST:event_btnRektActionPerformed

    private void btnTriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriaActionPerformed
        int x = (int) (Math.random() * 301);
        int y = (int) (Math.random() * 301);
        int b = (int) (Math.random() * 301);
        int h = (int) (Math.random() * 301);
        Form t = new Triangel(x, y, b, h, true);
        former.add(t);
        repaint();

    }//GEN-LAST:event_btnTriaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        this.former.clear();
        repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed
    // anropa draw metoden
    // Samt supperklassen med en bokstav
    // 

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < former.size(); i++) {
            former.get(i).draw(g);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirkel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRekt;
    private javax.swing.JButton btnTria;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}

